import os
import re
import time
import requests
from dotenv import load_dotenv
from utils.logger import get_logger

load_dotenv()
logger = get_logger("llm_client")

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
API_URL = "https://openrouter.ai/api/v1/chat/completions"

FREE_MODELS = [
    "meta-llama/llama-3.3-70b-instruct:free",
    "deepseek/deepseek-r1:free",
    "google/gemma-3-27b-it:free",
    "mistralai/mistral-small-3.1-24b-instruct:free",
    "qwen/qwen-2.5-72b-instruct:free",
]

_model_state = {
    model: {
        "requests_this_minute": 0,
        "minute_start": time.time(),
        "total_requests": 0,
        "last_429_at": 0,
        "blacklisted": False,
    }
    for model in FREE_MODELS
}

RPM_LIMIT = 18


# ──────────────────────────────────────────────
# RULE-BASED FALLBACK AGENTS (no API needed)
# ──────────────────────────────────────────────

def _rule_based_analysis(text: str) -> str:
    """Extract methodology, findings, limitations using regex + heuristics."""
    sentences = re.split(r'(?<=[.!?])\s+', text)
    
    method_keywords = ["method", "approach", "propose", "model", "algorithm", "architecture", "framework", "technique", "train", "dataset"]
    finding_keywords = ["result", "achieve", "outperform", "accuracy", "performance", "show", "demonstrate", "improve", "state-of-the-art", "beat"]
    limit_keywords = ["limitation", "future work", "however", "drawback", "constraint", "although", "not handle", "fail", "cannot"]

    methodology, findings, limitations = [], [], []

    for s in sentences:
        sl = s.lower()
        if any(k in sl for k in method_keywords) and len(methodology) < 3:
            methodology.append(s.strip())
        elif any(k in sl for k in finding_keywords) and len(findings) < 3:
            findings.append(s.strip())
        elif any(k in sl for k in limit_keywords) and len(limitations) < 2:
            limitations.append(s.strip())

    return f"""PAPER ANALYSIS (rule-based fallback):

METHODOLOGY:
{chr(10).join(f'- {m}' for m in methodology) if methodology else '- Could not extract automatically.'}

KEY FINDINGS:
{chr(10).join(f'- {f}' for f in findings) if findings else '- Could not extract automatically.'}

LIMITATIONS:
{chr(10).join(f'- {l}' for l in limitations) if limitations else '- Could not extract automatically.'}

Note: Generated by rule-based fallback (LLM API quota exceeded)."""


def _rule_based_summary(text: str) -> str:
    """Return first 5 meaningful sentences as summary."""
    sentences = re.split(r'(?<=[.!?])\s+', text)
    good = [s.strip() for s in sentences if len(s.strip()) > 40][:5]
    summary = ' '.join(good) if good else text[:500]
    return f"""SUMMARY (rule-based fallback):

{summary}

Note: Generated by rule-based fallback (LLM API quota exceeded)."""


def _rule_based_citations(text: str) -> str:
    """Extract citation-like patterns from text."""
    patterns = [
        r'\[[\d,\s]+\]',           # [1], [1,2,3]
        r'\([\w\s]+,\s*\d{4}\)',   # (Author, 2020)
        r'[\w\s]+et al\.,?\s*\d{4}',  # Author et al., 2020
    ]
    citations = []
    for pattern in patterns:
        found = re.findall(pattern, text)
        citations.extend(found)

    citations = list(dict.fromkeys(citations))[:15]  # deduplicate, limit 15

    return f"""CITATIONS (rule-based fallback):

{chr(10).join(f'- {c.strip()}' for c in citations) if citations else '- No citation patterns detected automatically.'}

Note: Generated by rule-based fallback (LLM API quota exceeded)."""


def _rule_based_insights(text: str) -> str:
    """Extract key insight sentences."""
    sentences = re.split(r'(?<=[.!?])\s+', text)
    insight_keywords = ["novel", "first", "key", "important", "significant", "contribution", "propose", "introduce", "new", "better", "faster", "efficient"]

    insights = []
    for s in sentences:
        sl = s.lower()
        if any(k in sl for k in insight_keywords) and len(insights) < 5:
            insights.append(s.strip())

    return f"""KEY INSIGHTS (rule-based fallback):

{chr(10).join(f'- {i}' for i in insights) if insights else '- Could not extract insights automatically.'}

Note: Generated by rule-based fallback (LLM API quota exceeded)."""


RULE_BASED_AGENTS = {
    "analysis":  _rule_based_analysis,
    "summary":   _rule_based_summary,
    "citations": _rule_based_citations,
    "insights":  _rule_based_insights,
}


def _detect_task(system_prompt: str, user_prompt: str) -> str:
    """Detect which rule-based agent to use from the prompt."""
    combined = (system_prompt + user_prompt).lower()
    if any(k in combined for k in ["citation", "reference", "bibliography"]):
        return "citations"
    if any(k in combined for k in ["insight", "contribution", "takeaway"]):
        return "insights"
    if any(k in combined for k in ["summary", "summarize", "overview"]):
        return "summary"
    return "analysis"


def _extract_paper_text(user_prompt: str) -> str:
    """Pull the actual paper text out of the user prompt."""
    # Common pattern: prompt has instructions then paper text after a separator
    for sep in ["---", "===", "Paper text:", "Text:", "\n\n"]:
        if sep in user_prompt:
            parts = user_prompt.split(sep, 1)
            if len(parts[1].strip()) > 100:
                return parts[1].strip()
    return user_prompt


# ──────────────────────────────────────────────
# MAIN LLM CALLER
# ──────────────────────────────────────────────

def _reset_minute(state):
    if time.time() - state["minute_start"] >= 60:
        state["requests_this_minute"] = 0
        state["minute_start"] = time.time()


def call_llm(system_prompt: str, user_prompt: str, max_retries: int = 3, temperature: float = 0.3) -> str:
    if not OPENROUTER_API_KEY:
        raise EnvironmentError("OPENROUTER_API_KEY not set in .env")

    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://github.com/manohar99-1/research-paper-analyzer",
        "X-Title": "Research Paper Analyzer"
    }

    for model in FREE_MODELS:
        state = _model_state[model]

        if state["blacklisted"]:
            continue

        _reset_minute(state)

        for attempt in range(1, max_retries + 1):
            _reset_minute(state)

            if state["requests_this_minute"] >= RPM_LIMIT:
                logger.warning(f"[{model.split('/')[-1]}] RPM limit hit, moving to next model")
                break

            payload = {
                "model": model,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                "temperature": temperature,
                "max_tokens": 2000
            }

            try:
                logger.debug(f"[{model.split('/')[-1]}] Attempt {attempt}/{max_retries}")
                response = requests.post(API_URL, headers=headers, json=payload, timeout=60)

                state["requests_this_minute"] += 1
                state["total_requests"] += 1

                if response.status_code == 429:
                    logger.warning(f"[{model.split('/')[-1]}] 429 rate limited. Skipping to next model.")
                    state["last_429_at"] = time.time()
                    break

                if response.status_code == 404:
                    logger.error(f"[{model.split('/')[-1]}] 404 not found. Blacklisting.")
                    state["blacklisted"] = True
                    break

                if response.status_code == 401:
                    raise EnvironmentError("Invalid OPENROUTER_API_KEY — check your secret.")

                if response.status_code == 402:
                    logger.error(f"[{model.split('/')[-1]}] 402 Payment Required. Blacklisting.")
                    state["blacklisted"] = True
                    break

                response.raise_for_status()
                data = response.json()
                content = data["choices"][0]["message"]["content"]
                logger.info(f"[{model.split('/')[-1]}] Success ({len(content)} chars)")
                return content.strip()

            except EnvironmentError:
                raise
            except requests.exceptions.Timeout:
                logger.error(f"[{model.split('/')[-1]}] Timeout on attempt {attempt}")
                time.sleep(2)
            except requests.exceptions.RequestException as e:
                logger.error(f"[{model.split('/')[-1]}] Error: {e}")
                time.sleep(2)
            except (KeyError, IndexError) as e:
                logger.error(f"[{model.split('/')[-1]}] Bad response format: {e}")
                break

    # ── ALL LLM MODELS FAILED — use rule-based fallback ──
    logger.warning("All LLM models failed. Switching to rule-based fallback agent.")
    task = _detect_task(system_prompt, user_prompt)
    paper_text = _extract_paper_text(user_prompt)
    fallback_fn = RULE_BASED_AGENTS[task]
    result = fallback_fn(paper_text)
    logger.info(f"Rule-based fallback [{task}] produced {len(result)} chars.")
    return result


def log_usage_summary():
    logger.info("── Model Usage Summary ──")
    for model, state in _model_state.items():
        short = model.split("/")[-1]
        status = "BLACKLISTED" if state["blacklisted"] else "ok"
        logger.info(f"  {short}: total={state['total_requests']}, rpm={state['requests_this_minute']}, status={status}")
